import { currentLanguageId } from '../../src/ui/i18n';

// The battle sim page is a dev tool. Its own labels live here in English and Chinese. Names of classes, monsters and spells come from t().
const TEXTS = {
  en: {
    title: 'Battle sim',
    language: 'Language',
    heroes: 'Heroes',
    heroClass: 'Class',
    heroLevel: 'Level',
    gear: 'Gear',
    'gear.none': 'No gear',
    'gear.weapon': 'Starting weapon only',
    'gear.common': 'Common best gear',
    'gear.magic': 'Magic best gear',
    secondHero: 'Add a second hero',
    secondClass: 'Second hero class',
    secondLevel: 'Second hero level',
    creeps: 'Creeps',
    creep: 'Creep',
    creepLevel: 'Creep level',
    creepCount: 'Count',
    'rank.normal': 'Normal',
    'rank.rare': 'Rare',
    'rank.boss': 'Boss',
    seed: 'Seed',
    randomSeed: 'Random seed',
    start: 'Start',
    restart: 'Restart',
    pause: 'Pause',
    resume: 'Resume',
    speed: 'Speed',
    monteCarlo: 'Run 20 battles',
    monteCarloResult: '{battles} battles: win rate {winRate}%, average {seconds} s, average HP lost {hpLost}%',
    heroStats: 'Hero stats',
    creepStats: 'Creep stats',
    hp: 'HP',
    damage: 'Damage',
    defence: 'Defence',
    armour: 'Armour',
    resistance: 'Resistance',
    attackTime: 'Attack time',
    crit: 'Crit',
    moveSpeed: 'Move speed',
    range: 'Range',
    melee: 'melee',
    spells: 'Spells',
    live: 'Live',
    log: 'Event log',
    summary: 'Summary',
    waiting: 'Press Start.',
    winner: 'Winner',
    'winner.party': 'Heroes',
    'winner.enemy': 'Creeps',
    duration: 'Duration',
    hpLost: 'HP lost (heroes)',
    damageDealt: 'Damage dealt',
    damagePerSecond: 'Damage per second',
    healingDone: 'Healing',
    unit: 'Unit',
    seconds: 's',
  },
  zh: {
    title: '战斗模拟',
    language: '语言',
    heroes: '英雄',
    heroClass: '职业',
    heroLevel: '等级',
    gear: '装备',
    'gear.none': '无装备',
    'gear.weapon': '只有初始武器',
    'gear.common': '普通品质最佳装备',
    'gear.magic': '魔法品质最佳装备',
    secondHero: '添加第二名英雄',
    secondClass: '第二名英雄职业',
    secondLevel: '第二名英雄等级',
    creeps: '怪物',
    creep: '怪物',
    creepLevel: '怪物等级',
    creepCount: '数量',
    'rank.normal': '普通',
    'rank.rare': '稀有',
    'rank.boss': '首领',
    seed: '种子',
    randomSeed: '随机种子',
    start: '开始',
    restart: '重新开始',
    pause: '暂停',
    resume: '继续',
    speed: '速度',
    monteCarlo: '运行20场战斗',
    monteCarloResult: '{battles}场战斗：胜率{winRate}%，平均{seconds}秒，平均损失生命{hpLost}%',
    heroStats: '英雄属性',
    creepStats: '怪物属性',
    hp: '生命',
    damage: '伤害',
    defence: '防御',
    armour: '护甲',
    resistance: '抗性',
    attackTime: '攻击间隔',
    crit: '暴击',
    moveSpeed: '移动速度',
    range: '射程',
    melee: '近战',
    spells: '法术',
    live: '实时',
    log: '事件记录',
    summary: '总结',
    waiting: '按开始。',
    winner: '胜者',
    'winner.party': '英雄',
    'winner.enemy': '怪物',
    duration: '时长',
    hpLost: '损失生命（英雄）',
    damageDealt: '造成伤害',
    damagePerSecond: '每秒伤害',
    healingDone: '治疗',
    unit: '单位',
    seconds: '秒',
  },
} as const;

export type SimTextKey = keyof (typeof TEXTS)['en'];

export function say(key: SimTextKey, params: Record<string, string | number> = {}): string {
  const table: Record<string, string> = TEXTS[currentLanguageId()];
  return (table[key] ?? key).replace(/\{(\w+)\}/g, (placeholder, name: string) => String(params[name] ?? placeholder));
}
