export const MAXIMUM_MONSTERS_PER_ENCOUNTER = 3;
export const MAXIMUM_BOSS_ADDS = 2;
export const RARE_MONSTER_CHANCE = 0.02;

export const HEAL_BETWEEN_ENCOUNTERS_FRACTION = 0.2;
export const PARTY_WEAKENED_BELOW_AVERAGE_HEALTH = 0.3;

export const BACKPACK_COLUMNS = 10;
export const BACKPACK_ROWS = 8;
export const BACKPACK_CELL_CAPACITY = BACKPACK_COLUMNS * BACKPACK_ROWS;
export const MATERIAL_STACK_LIMIT = 99;
