export const MAXIMUM_MONSTERS_PER_ENCOUNTER = 3;
export const MAXIMUM_BOSS_ADDS = 2;
export const RARE_MONSTER_CHANCE = 0.02;

export const HEAL_BETWEEN_ENCOUNTERS_FRACTION = 0.2;
export const PARTY_WEAKENED_BELOW_AVERAGE_HEALTH = 0.3;
